### PR TITLE
If statement helps to make decision while executing program

### PR DESCRIPTION
**Pull request by akshay037**
This PR show the use of If statement, Using if and else condition it helps to execute certain condition are true and other condition are true.

### CODE REVIEW

**Comment by iamargentum** [comment]
try to make your commit messages more action-oriented
here's an example -

the message of first commit in this PR is - `If statement helps to make decision while executing program`

this is an explanatory commit message

it is generally appreciated if your commit messages say what changes have been made in the code, or in this case, when the entire file is new, what things have been implemented in this newly created file

so, here's something that i would write -

`Implement if, else and elif to understand control structures in Python`

**Comment by akshay037** [comment]
Got it sir I was focused on making the commit message understood to a new
person but next time
I'll be focused on the things as follows
1.  Message understood to a new person
2. What the actually PR show the work done

**Comment by iamargentum** [comment]
perfecto!

**Comment by akshay037** [comment]
Thank you sir !

**Pull request merged**
